- name: task level varibales
  hosts: localhost
  tasks:
  - name: task variable
    vars:
     trainer: "ram"
     course: "terromform"
     duration: "15hrs"
    ansible.builtin.debug:
     msg: "hi, i am learning {{course}} from {{trainer}} duration {{duration}}."
  
       