- name: variables from file
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name:
     ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}." 