- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: username
    prompt: "enter user name"
    private: false
  - name: password
    prompt: "enterpassword"  
    private: true
  tasks:
  - name: print information
    ansible.builtin.debug:
     msg: "Hi, Username: {{USERNAME}}. Password is: {{PASSWORD}}"  