- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: user
    ignore_error: true
  
  - name: print user
    ansible.builtin.debug:
     msg: "user info: {{ user }}"  

  - name: create user
    ansible.builtin.command: adduser expense
    when: user.rc != 0 #if user not exist create user condition just with when


